### ISSUE TITLE
Initial setup for Backend

### ISSUE THREAD

**Issue by SaiKumarMalve** [SaiKumarMalve/Gator-News#4]
Initial setup for Backend
- Go drivers
- MongoDB
- Postman

**Comment by Alekhyagnv** [comment]
Downloaded and installed vscode ,golang.
Created a separate folder for Go project.
I have set the environment variable and path variable for Go.

**Comment by Alekhyagnv** [comment]
Downloaded and installed vscode ,golang.
Created a separate folder for Go project.
I have set the environment variable and path variable for Go.
